from .colors import *

water_animation = []

water_animation.append(
    [
        [OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF],
        [OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF],
        [OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF],
        [OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF],
        [OFF, OFF, OFF, OFF, MAGENTA, MAGENTA, OFF, OFF, OFF, OFF, OFF],
        [OFF, OFF, OFF, OFF, MAGENTA, MAGENTA, OFF, OFF, OFF, OFF, OFF],
        [OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF],
        [OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF],
        [OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF],
        [OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF],
    ]
)

water_animation.append(
    [
        [OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF],
        [OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF],
        [OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF],
        [OFF, OFF, OFF, MAGENTA, MAGENTA, MAGENTA, MAGENTA, OFF, OFF, OFF, OFF],
        [OFF, OFF, OFF, MAGENTA, OFF, OFF, MAGENTA, OFF, OFF, OFF, OFF],
        [OFF, OFF, OFF, MAGENTA, OFF, OFF, MAGENTA, OFF, OFF, OFF, OFF],
        [OFF, OFF, OFF, MAGENTA, MAGENTA, MAGENTA, MAGENTA, OFF, OFF, OFF, OFF],
        [OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF],
        [OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF],
        [OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF],
    ]
)


for i in range(20):
    water_animation.append(
        [
            [OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF],
            [OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF],
            [OFF, OFF, MAGENTA, MAGENTA, MAGENTA, MAGENTA, MAGENTA, MAGENTA, OFF, OFF, OFF],
            [OFF, OFF, MAGENTA, OFF, OFF, OFF, OFF, MAGENTA, OFF, OFF, OFF],
            [OFF, OFF, MAGENTA, OFF, OFF, OFF, OFF, MAGENTA, OFF, OFF, OFF],
            [OFF, OFF, MAGENTA, OFF, OFF, OFF, OFF, MAGENTA, OFF, OFF, OFF],
            [OFF, OFF, MAGENTA,OFF, OFF, OFF, OFF, MAGENTA, OFF, OFF, OFF],
            [OFF, OFF, MAGENTA, MAGENTA, MAGENTA, MAGENTA, MAGENTA, MAGENTA, OFF, OFF, OFF],
            [OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF],
            [OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF],
        ]
    )

    water_animation.append(
        [
            [OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF],
            [OFF, MAGENTA, MAGENTA, MAGENTA, MAGENTA, MAGENTA, MAGENTA, MAGENTA, MAGENTA, OFF, OFF],
            [OFF, MAGENTA, OFF, OFF, OFF, OFF, OFF, OFF, MAGENTA, OFF, OFF],
            [OFF, MAGENTA, OFF, OFF, OFF, OFF, OFF, OFF, MAGENTA, OFF, OFF],
            [OFF, MAGENTA, OFF, OFF, MAGENTA, MAGENTA, OFF, OFF, MAGENTA, OFF, OFF],
            [OFF, MAGENTA, OFF, OFF, MAGENTA, MAGENTA, OFF, OFF, MAGENTA, OFF, OFF],
            [OFF, MAGENTA, OFF, OFF, OFF, OFF, OFF, OFF, MAGENTA, OFF, OFF],
            [OFF, MAGENTA, OFF, OFF, OFF, OFF, OFF, OFF, MAGENTA, OFF, OFF],
            [OFF, MAGENTA, MAGENTA, MAGENTA, MAGENTA, MAGENTA, MAGENTA, MAGENTA, MAGENTA, OFF, OFF],
            [OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF],
        ]
    )

    water_animation.append(
        [
            [MAGENTA, MAGENTA, MAGENTA, MAGENTA, MAGENTA, MAGENTA, MAGENTA, MAGENTA, MAGENTA, MAGENTA, OFF],
            [MAGENTA, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, MAGENTA, OFF],
            [MAGENTA, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, MAGENTA, OFF],
            [MAGENTA, OFF, OFF, MAGENTA, MAGENTA, MAGENTA, MAGENTA, OFF, OFF, MAGENTA, OFF],
            [MAGENTA, OFF, OFF, MAGENTA, OFF, OFF, MAGENTA, OFF, OFF, MAGENTA, OFF],
            [MAGENTA, OFF, OFF, MAGENTA, OFF, OFF, MAGENTA, OFF, OFF, MAGENTA, OFF],
            [MAGENTA, OFF, OFF, MAGENTA, MAGENTA, MAGENTA, MAGENTA, OFF, OFF, MAGENTA, OFF],
            [MAGENTA, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, MAGENTA, OFF],
            [MAGENTA, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, MAGENTA, OFF],
            [MAGENTA, MAGENTA, MAGENTA, MAGENTA, MAGENTA, MAGENTA, MAGENTA, MAGENTA, MAGENTA, MAGENTA, OFF],
        ]
    )